from typing import List
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse

from app.schemas.ollama import (
    ChatRequest,
    ChatResponse,
    GenerateRequest,
    GenerateResponse,
    ModelInfo,
    OllamaHealthResponse,
)
from app.services.ollama_service import OllamaServiceException, ollama_service

router = APIRouter(prefix="/ollama", tags=["Ollama / Gemma"])


@router.get(
    "/health",
    response_model=OllamaHealthResponse,
    summary="Check Ollama connection and list local models",
)
async def check_health():
    """Verify if the local Ollama instance is reachable and view available models."""
    return await ollama_service.check_health()


@router.get(
    "/models",
    response_model=List[ModelInfo],
    summary="List available local Ollama models",
)
async def list_models():
    """Get all installed models in the local Ollama instance."""
    try:
        return await ollama_service.list_models()
    except OllamaServiceException as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)


@router.post(
    "/generate",
    response_model=GenerateResponse,
    summary="Generate text completion with Gemma",
)
async def generate(request: GenerateRequest):
    """Generate a full text response from Gemma for a given prompt."""
    try:
        return await ollama_service.generate(request)
    except OllamaServiceException as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)


@router.post(
    "/generate/stream",
    summary="Stream text completion with Gemma",
)
async def generate_stream(request: GenerateRequest):
    """Stream token chunks as they are generated by Gemma."""
    try:
        generator = ollama_service.generate_stream(request)
        return StreamingResponse(generator, media_type="text/plain")
    except OllamaServiceException as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)


@router.post(
    "/chat",
    response_model=ChatResponse,
    summary="Send chat messages to Gemma",
)
async def chat(request: ChatRequest):
    """Send conversation history to Gemma and receive the assistant's reply."""
    try:
        return await ollama_service.chat(request)
    except OllamaServiceException as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)


@router.post(
    "/chat/stream",
    summary="Stream chat completion with Gemma",
)
async def chat_stream(request: ChatRequest):
    """Stream conversation replies from Gemma token-by-token."""
    try:
        generator = ollama_service.chat_stream(request)
        return StreamingResponse(generator, media_type="text/plain")
    except OllamaServiceException as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)
